pipeline:
  docker:
    image: plugins/docker
    repo: omerxx/drone-cloudformation-update
    tags: 
      - ${DRONE_BUILD_NUMBER}
      - drove-test
    secrets:
      - docker_username
      - docker_password

